---
- name: "set up docker"
  include_role:
        name: docker

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install packages
  become: true
  apt:
    state: latest
    name:
      - nfs-common
      - nginx
      - rsync
      - kubectl

- name: Create mount directory
  become: true
  file:
    path: "{{ data_dir }}"
    state: directory
  when: nfs_mount is defined

- name: Mount an NFS volume
  become: true
  mount:
    src: "{{ nfs_mount }}"
    path: "{{ data_dir }}"
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs
  when: nfs_mount is defined

- name: Create pipeline directory
  become: true
  file:
    path: /opt/pipeline/data
    state: directory

# ngnix
# - name: Creates directory
#   file:
#     path: /opt
#     state: directory

# - name: copy code
#   become: true
#   synchronize:
#     src: /home/mwm1/Work/pipeline_coordination/restart_pods
#     dest: /opt/pipeline_coordination
#     rsync_opts:
#       - "--exclude=.direnv"

# - name: copy code
#   become: true
#   template:
#     src: templates/default
#     dest: /etc/nginx/sites-enabled/default
#   notify:
#     - restart nginx
