---
# tasks file for nfs
# see :
#   https://github.com/takara9/vagrant-nfs
#   https://www.tecmint.com/install-nfs-server-on-ubuntu/
#   https://advishnuprasad.com/blog/2016/03/29/setup-nfs-server-and-client-using-ansible/
- name: common role
  include_role:
        name: common

- name: nfs - install apt packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    update_cache: yes

- name: nfs - make share directory
  ansible.builtin.file:
    path: "{{ nfs_share_directory }}"
    owner:  pheweb
    group: pheweb
    mode: '0777'
    state: directory

- name: nfs - create export configuration
  template:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: nfs - make pheweb directory
  ansible.builtin.file:
    path: "{{ nfs_pheweb_directory }}"
    owner:  pheweb
    group: pheweb
    mode: '0777'
    state: directory

- name: change owner to pheweb
  ansible.builtin.file:
    path: "{{ nfs_share_directory }}"
    owner:  pheweb
    group: pheweb
    recurse: yes

- name: nfs - copy bucket
  ansible.builtin.command:
  args:
    cmd: gsutil -m rsync -R "{{ nfs_bucket_directory }}" "{{ nfs_pheweb_directory }}"
  when: bucket_directory is defined

- name: nfs - restart nfs server
  service: name=nfs-kernel-server state=restarted

- name: r4 specific tasks
  import_tasks: r4.yaml
  when: release is defined and release == "r4"
