---
# tasks file for nfs
# see :
#   https://github.com/takara9/vagrant-nfs
#   https://www.tecmint.com/install-nfs-server-on-ubuntu/
#   https://advishnuprasad.com/blog/2016/03/29/setup-nfs-server-and-client-using-ansible/

- name: nfs - install apt packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    update_cache: yes


- name: nfs - make share directory
  ansible.builtin.file:
    path: /data/pheweb
    owner:  nobody
    group: nogroup
    mode: '0777'
    state: directory
  
- name: nfs - create export configuration
  copy: 
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: nfs - make share directory
  ansible.builtin.file:
    path: /data/pheweb/r1
    owner:  nobody
    group: nogroup
    mode: '0777'
    state: directory

- name: nfs - copy bucket
  ansible.builtin.command:
  args:
    cmd: gsutil -m cp -R gs://r9_data_green/development /data/pheweb/r1
    creates: /data/pheweb/r1/config.py
  
#- name: nfs - crontab bucket
# gsutil -m rsync -R gs://r9_data_green/development/ /data/pheweb/r1 
- name: nfs - restart nfs server
  service: name=nfs-kernel-server state=restarted
