apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ig-{{ .Values.pheweb.subdomain }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ if .Values.pheweb.ipName }} "{{ .Values.pheweb.ipName }}" {{ else }} "{{ .Values.pheweb.subdomain }}"  {{ end }}
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
  labels:
    app: pheweb
spec:
  tls:
  - hosts:
    - {{ .Values.pheweb.subdomain }}.finngen.fi
    secretName: finngen-tls
  rules:
  - host: {{ .Values.pheweb.subdomain }}.finngen.fi
    http:
      paths:
      - backend:
          serviceName: {{ include "pheweb.fullname" . }}-front
          servicePort: 80
        path: /*
