apiVersion: v1
kind: Service
metadata:
  name: {{ include "pheweb.fullname" . }}-front
  labels:
    app: pheweb
    tier: frontend
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"serviceproxy-backendconfig"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pheweb
    tier: frontend
