---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: serviceproxy-backendconfig
spec:
  timeoutSec: 7200

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pheweb.fullname" . }}-front
  labels:
    app: pheweb
    tier: frontend
    product : pheweb-{{ .Values.pheweb.deployment }}-{{ .Values.pheweb.release }}
    release: {{ .Values.pheweb.release }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"serviceproxy-backendconfig"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pheweb
    tier: frontend
