# Default values are found in values.yaml

replicaCount: 1

pheweb:
  mount: /mnt/nfs
  subdomain: metaresults-ukbb
  ipName: finngen-metaresults-ukbb-ip
  release: r7
  
persistentVolume:
  storage: 11T
  path: /vol1
  server: 10.179.247.250
