# Default values are found in values.yaml

replicaCount: 2

pheweb:
  mount: /mnt/nfs
  subdomain: r5
  ipName: finngen-r5-ip
  release: r5
  
persistentVolume:
  storage: 11T
  path: /vol1
  server: 10.179.247.250

image:
  tag: ci-f78dca68080083c101b63c53a2b8890481381df5