# Default values are found in values.yaml

replicaCount: 2

pheweb:
  mount: /mnt/nfs
  subdomain: userresults
  cloudSQLCredentialFile: /mnt/nfs/pheweb/phewas.sql.credentials.json
  cloudSQLProxyInstances: phewas-development:europe-west1:dev-db1=tcp:3306
  ipName: sandbox-gwas
  release: r7
  
persistentVolume:
  path: /vol1
  server: 10.179.247.250
