pheweb:
  ssl: true
  health: true
  deployment: production
  
image: # pheweb image
  repository: gcr.io/phewas-development/pheweb
  pullPolicy: IfNotPresent
  tag: ci-6ddb9e2bb7ef56e8fd4c72f44f24ef3e03c6d057

service:
  type: NodePort
  port: 80

persistentVolume:
  storage: 11T
