version: '2'
services:
  cromwell:
    build:
      context: ./compose/cromwell
    volumes:
      - ./cromwell-executions:/cromwell-working-dir/cromwell-executions
    command: ["java -Dconfig.file=/app-config/cromwell-application.conf -jar /app/cromwell.jar server"]
    ports:
      - "80:8000"
