imports:
- path: phweb-instance-nfs.jinja
- path: phweb-kubernetes.jinja
  
resources:
- name: phweb-instance-nfs-template
  type: phweb-instance-nfs.jinja
  properties:
    release: userresults
    environment: production
    nfsDiskSizeGb: 2000
    serviceAccount: pheweb@phewas-development.iam.gserviceaccount.com

- name: phweb-kubernetes-template
  type: phweb-kubernetes.jinja
  properties:
    release: userresults
    environment: production
