resources:

# - name: dev-r9-pheweb-ip
#   type: compute.v1.address
#   properties:
#     region: global
#      metadata:
#       items:
#         - key: product
#           value: pheweb-production-r9

- name: prod-r9-pheweb-kubernetes
  type: container.v1.cluster
  properties:
    zone: europe-west1-b
    cluster:
      name: prod-r9-pheweb-kubernetes
      description: >-
        Kubernetes cluster for r9 pheweb
      nodePools:
        - name: prod-r9-pheweb-pool
          initialNodeCount: 1
          config:
            machineType: n1-standard-1
            oauthScopes:
              - https://www.googleapis.com/auth/devstorage.read_only
              - https://www.googleapis.com/auth/logging.write
              - https://www.googleapis.com/auth/monitoring
              - https://www.googleapis.com/auth/servicecontrol
              - https://www.googleapis.com/auth/service.management.readonly
              - https://www.googleapis.com/auth/trace.append
          locations:
            - europe-west1-b
          management:
            autoUpgrade: true
            autoRepair: true
      network: default
      resourceLabels:
        product : pheweb-production-r9
- name: prod-r9-pheweb-nfs
  type: gcp-types/file-v1beta1:projects.locations.instances
  properties:
    parent: projects/phewas-development/locations/europe-west1-b
    instanceId: prod-r9-pheweb-nfs
    tier: STANDARD
    description: >-
      Browser data for r9 data freeze
      FinnGen and meta summary stats
      and other PheWeb generated data
    networks:
    - network: default
    fileShares:
    - name: pheweb
      capacityGb: 1024
    labels:
      product: r9-pheweb-nfs
