imports:
- path: phweb-instance-nfs.jinja
- path: phweb-kubernetes.jinja
  
resources:
- name: phweb-instance-nfs-template
  type: phweb-instance-nfs.jinja
  properties:
    release: r4
    environment: production
    nfsDiskSizeGb: 2750

- name: phweb-kubernetes-template
  type: phweb-kubernetes.jinja
  properties:
    release: r4
    environment: production
