apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv-0
spec:
  capacity:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: finngen-r4-results-full-0
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-0
spec:
  storageClassName: ""
  volumeName: pheweb-pv-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
