apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv
spec:
  capacity:
      storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: finngen-r3-results-v2-0
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-0
spec:
  storageClassName: ""
  volumeName: pheweb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1800Gi
