apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv-0
spec:
  capacity:
      storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: pheweb-r2-0
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-0
spec:
  storageClassName: ""
  volumeName: pheweb-pv-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv-1
spec:
  capacity:
      storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: pheweb-r2-1
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-1
spec:
  storageClassName: ""
  volumeName: pheweb-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv-2
spec:
  capacity:
      storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: pheweb-r2-2
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-2
spec:
  storageClassName: ""
  volumeName: pheweb-pv-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pheweb-pv-3
spec:
  capacity:
      storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: pheweb-r2-3
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheweb-pv-pheweb-front-3
spec:
  storageClassName: ""
  volumeName: pheweb-pv-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
