- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install packages
  become: true
  apt:
    state: latest
    name:
      - git
      - nfs-common
      - nginx
      - direnv
      - virtualenv
      - rsync
      - kubectl
      - pwgen
      - python-pip
      - python3-pip
      - libblas3
      - liblapack3
      - liblapack-dev
      - libblas-dev
      - gfortran

- name: nfs_dev create mount directory
  become: true
  file:
    path: /mnt/nfs_dev
    state: directory

- name: nfs create mount directory
  become: true
  file:
    path: /mnt/nfs
    state: directory

- name: nfs check that the somefile.conf exists
  stat:
    path: /mnt/nfs/pheweb
  register: nfs_directory

- name: nfs mount an NFS volume
  become: true
  mount:
    src: 10.179.247.250:/vol1
    path: /mnt/nfs
    opts: ro,sync,hard,intr
    state: mounted
    fstype: nfs
  when: not nfs_directory.stat.exists

- name: apt install python package
  become: true
  apt:
    state: latest
    name:
      - python3
      - python3-setuptools
      - python3-boltons
      - python3-pysam
      - python3-gevent
      - python3-pip

- name: apt install pheweb package
  become: true
  apt:
    state: latest
    name:
      - default-libmysqlclient-dev
      - libffi-dev
      - libz-dev
      - libssl-dev
      - libbz2-dev
      - liblzma-dev
      - rustc
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: work directory
  become: true
  file:
    path: "{{ansible_env.PWD}}/Work"
    state: directory
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: checkout phweb
  ansible.builtin.git:
    repo: https://github.com/FINNGEN/pheweb
    dest: "{{ansible_env.PWD}}/Work/pheweb"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: install pheweb
  shell: cd {{ansible_env.PWD}}/Work/pheweb; pip3 install .
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"
