apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
      storage: 5T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /vol1
    server: 10.179.247.250
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5T
