---
- name: "set up docker"
  include_role:
        name: docker

- name: install mariadb
  become: true
  apt:
    state: latest
    update_cache: yes
    name:
      - mariadb-server
      - python3-pymysql

- name: setting database facts
  ansible.builtin.set_fact:
    db_user: "cromwell"
    db_name: "cromwell"
    db_host: "localhost"
    cromwell_zone: "europe-west1-b"
    cromwell_project: "{{ cromwell_project }}"
    cromwell_task_zone: "TODO array"
    cromwell_bucket: "{{ cromwell_bucket }}"
    docker_image: "{{ cromwell_docker_image | default('broadinstitute/cromwell:84-dbe3a31') }}"
    docker_name: "cromwell"
    db_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"


- name: template mysql configuration
  become: yes
  template:
    src: roles/cromwell/templates/my.cnf
    dest: /root/.my.cnf
    owner: root
    group: root

- name: Create a new database with name 'cromwell'
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    state: present

- name: Create user with password, all database privileges
  community.mysql.mysql_user:
    state: present
    name: "{{ db_user }}"
    host: localhost
    password: "{{ db_password }}"
    priv:
      "{{ db_name }}.*:ALL"

- name: add group cromwell
  become: yes
  group:
    name: cromwell
    state: present

- name: add group cromwell
  become: yes
  user:
    name: cromwell
    groups: cromwell,docker
    state: present

- name: Creates cromwell root directory
  file:
    path: /opt/cromwell
    state: directory

- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/cromwell/cromwell-working-dir/cromwell-executions
    - /opt/cromwell/app-config

- name: template configuration
  become: yes
  template:
    src: roles/cromwell/templates/application.conf.j2
    dest: /opt/cromwell/app-config/cromwell-application.conf
    owner: cromwell
    group: cromwell

- name: create a data container
  community.docker.docker_container:
    name: "{{ docker_name }}"
    image: "{{ cromwell_docker_image }}"
    restart_policy: "on-failure"
    restart_retries: 10
    network_mode: host
    volumes:
      - "/opt/cromwell/app-config:/app-config"
      - "/opt/cromwell/cromwell-working-dir/cromwell-executions:/cromwell-working-dir/cromwell-executions"
    ports:
      - "80:8000"
    entrypoint:
      - /opt/java/openjdk/bin/java
      - -Xmx8G
      - -Dconfig.file=/app-config/cromwell-application.conf
      - -jar
      - /app/cromwell.jar
      - server
