image:
  tag: ci-f7490aec688bb4cdebd3555f08409552d6b3eac1

persistentVolume:
  path: /data/nfs/pheweb
  server: 10.132.0.39

pheweb:
  cloudSQLCredentialFile: /etc/gcp/cloud-sql-credentials.json
  cloudSQLProxyInstances: phewas-development:europe-west1:dev-db1=tcp:3306
  directory: /mnt/userresults/release
  ipName: sandbox-gwas
  mount: /mnt
  release: userresults
  secretName: production-userresults-secrets
  subdomain: userresults
replicaCount: 2