
# Default values are found in values.yaml

replicaCount: 3

pheweb:
  cloudSQLCredentialFile: /etc/gcp/cloud-sql-credentials.json
  cloudSQLProxyInstances: phewas-development:europe-west1:dev-db1=tcp:3306
  directory: /mnt/nfs/pheweb/r7
  ipName: finngen-r7-ip
  mount: /mnt/nfs
  release: r7
  secretName: production-r7-secrets
  subdomain: r7
  tag: ci-939b9f1d70035ac541019f1f8d3ebab6a4875f45
  
persistentVolume:
  path: /data/nfs
  server: 10.132.0.132
  storage: 11T
