
# Default values are found in values.yaml

replicaCount: 2

pheweb:
  ipName: finngen-r5-ip
  mount: /mnt/nfs
  release: r5
  secretName: production-r5-secrets
  subdomain: r5
  
persistentVolume:
  path: /vol1
  server: 10.179.247.250
  storage: 11T

image:
  tag: ci-f78dca68080083c101b63c53a2b8890481381df5
       
