pheweb:
  ssl: true
  health: true
  deployment: production
  
image: # pheweb image
  repository: eu.gcr.io/phewas-development/pheweb
  pullPolicy: IfNotPresent
  tag: ci-939b9f1d70035ac541019f1f8d3ebab6a4875f45

service:
  type: NodePort
  port: 80

persistentVolume:
  storage: 11T
